version: '1'
services:
    postgres:
        container_name: policia_db
        image: postgres:17
        restart: unless-stopped
        ports:
            - '5442:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:
